version: '3'
services:
  go:
    image: vimagick/shadowsocks:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - nginx

  nginx:
    image: alaien/nginx_tcp_stream:latest
    ports:
      - 9000:80
    networks:
      - nginx
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy: 
        condition: on-failure
    depends_on:
      - go
    volumes:
      - /root/nginx_conf/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
networks:
  nginx:
