version: '3.3'
services:
  viz:
    image: bretfisher/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
  go:
    image: vimagick/shadowsocks
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - PASSWORD=123
    networks:
      - nginx

  nginx:
    image: alaien/nginx_tcp_stream
    ports:
      - 9000:80
    networks:
      - nginx
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      restart_policy: 
        condition: on-failure
    depends_on:
      - go
    configs:
      - source: nginx_conf-1
        target: /usr/local/nginx/conf/nginx.conf
networks:
  nginx:
configs:
  nginx_conf-1:
    file: ./nginx.conf
