version: '3'
services:
  go:
    image: vimagick/shadowsocks:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - nginx

  nginx:
    image: tcp_nginx:latest
    ports:
      - 9000:80
    networks:
      - nginx
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy: 
        condition: on-failure
    depends_on:
      - go
networks:
  nginx:
